LSXHelpers = LSXHelpers or {}

---@return LSXNode?
function LSXHelpers.new()
    local save = {
        version = {
            major = 4,
            minor = 8,
            revision = 0,
            build = 400,
            lslib_meta = "v1,bswap_guids,lsf_keys_adjacency"
        },
    }

    local root = LSXNode.new("save")
    local versionNode = root:AppendChild(
        LSXNode.new("version", {
            major = save.version.major,
            minor = save.version.minor,
            revision = save.version.revision,
            build = save.version.build,
            lslib_meta = save.version.lslib_meta
        })
    )
    versionNode:SetAttrOrder({"major", "minor", "revision", "build", "lslib_meta"})

    if not versionNode then
        Error("LSXUtils.new: Could not create LSXTableNode")
        return nil
    end

    versionNode:AddComment("This file was generated by Script Extender")

    return root
end


function LSXHelpers.MakeItemLSX(guid, modName)
    local curLevel = _C().Level.LevelName
    local propData = EntityStore:GetEntity(guid)
    local entity = Ext.Entity.Get(guid)
    if not propData then
        Error("MakePropLSX: No prop data found for GUID " .. tostring(guid))
        return nil
    end

    local root = LSXHelpers.new()
    if not root then
        Error("MakePropLSX: Failed to create LSX root node.")
        return nil
    end

    local regionWrapper = LSXHelpers.RegionNodeWrapper("Templates", root)

    local firstChildren = regionWrapper:AppendChild(LSXNode.new("Children"))

    local gameObjectNode = firstChildren:AppendChild(LSXNode.new("node", { id = "GameObjects" }))

    local basicAttrs = {
        LSXHelpers.AttrNode("MapKey", "FixedString", guid),
        LSXHelpers.AttrNode("Name", "LSString", propData.DisplayName or TrimTail(propData.TemplateId, 37)),
        LSXHelpers.AttrNode("LevelName", "FixedString", curLevel),
        LSXHelpers.AttrNode("Type", "FixedString", "item"),
        LSXHelpers.AttrNode("TemplateName", "FixedString", TakeTailTemplate(propData.TemplateId)),
        LSXHelpers.AttrNode("GravityType", "uint8", propData.Gravity and 0 or 1),
    }

    gameObjectNode:AppendChildren(basicAttrs)

    local secondChidren = gameObjectNode:AppendChild(LSXNode.new("Children"))

    local transformNode = secondChidren:AppendChild(LSXNode.new("node", { id = "Transform" }))


    local pos = {CGetPosition(guid)}
    local rot = {CGetRotation(guid)}
    local scale = {CGetScale(guid)}
    local smallestScale = math.min(scale[1], scale[2], scale[3])

    local transformAttrs = {
        LSXHelpers.AttrNode("Position", "fvec3", pos),
        LSXHelpers.AttrNode("RotationQuat", "fvec4", rot),
        LSXHelpers.AttrNode("Scale", "float", smallestScale),
    }

    transformNode:AppendChildren(transformAttrs)


    local layerListNode = secondChidren:AppendChild(LSXNode.new("node", { id = "LayerList" }))

    local layerFirstChildren = layerListNode:AppendChild(LSXNode.new("Children"))

    local layerNode = layerFirstChildren:AppendChild(LSXNode.new("node", { id = "Layer" }))

    local layerSecondChildren = layerNode:AppendChild(LSXNode.new("Children"))

    local objectNode = layerSecondChildren:AppendChild(LSXNode.new("node", { id = "Object", key = "MapKey" }))

    local layerAttr = {
        LSXHelpers.AttrNode("MapKey", "FixedString", curLevel),
    }

    objectNode:AppendChildren(layerAttr)

    if not modName then
        modName = "Mods"
    end

    local path = string.format("Realm_Builder/LSX/%s/Mods/%s/Levels/%s/items/%s", modName, modName, curLevel, propData.DisplayName)

    --- Sanitize path
    path:gsub("[<>:\"/\\|%?%*]", "_")

    local suc = Ext.IO.SaveFile(path, root:Stringify())

    if not suc then
        Error("MakePropLSX: Failed to save LSX file at " .. path)
        return nil
    end

    return suc
end

---@param marerialPresetUUID GUIDSTRING
---@param displayName string
---@param internalName string
---@param UIColor string
---@param presetType "EyeColor"|"HairColor"|"SkinColor"
---@return LSXNode
function LSXHelpers.MakeCharacterCreationLSXNode(marerialPresetUUID, displayName, internalName, UIColor, presetType)
    local node = LSXNode.new("node", { id = "CharacterCreation"..presetType })

    local attrs = {
        LSXHelpers.AttrNode("DisplayName", "TranslatedString", displayName),
        LSXHelpers.AttrNode("MaterialPresetUUID", "guid", marerialPresetUUID),
        LSXHelpers.AttrNode("Name", "FixedString", internalName),
        LSXHelpers.AttrNode("UIColor", "LSString", UIColor),
        LSXHelpers.AttrNode("UUID", "guid", Ext.Utils.GenerateGUID()),
    }

    node:AppendChildren(attrs)

    return node
end

---@param regionName string
---@return LSXNode
function LSXHelpers.RegionNodeWrapper(regionName, parent)
    local regionNode = LSXNode.new("region", {id = regionName})

    if parent then
        parent:AppendChild(regionNode)
    end

    local node = LSXNode.new("node", {id = regionName})
    regionNode:AppendChild(node)
    return node
end

---@param id any
---@param type LSXValueType
---@param value any
---@return LSXNode
function LSXHelpers.AttrNode(id, type, value)
    local attrNode = LSXNode.new("attribute", {
        id = id,
        type = type,
        value = value,
    })
    attrNode:SetAttrOrder({"id", "type", "value"})
    return attrNode
end

--- so this basically generates an LSX file like:
--- <?xml version="1.0" encoding="utf-8"?>
--- <contentList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
---   <content contentuid="generated-guid" version="1">name1</content>
---   <content contentuid="generated-guid" version="1">name2</content>
---  ...
--- </contentList>
--- which is the localization used by the game
---@param names string[]
---@param version number|fun(name:string):number
---@return string, table<string, string>, table<string, string>
function LSXHelpers.GenerateLocalization(names, version)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })
    local stringToHandle = {}
    local handleToString = {}

    for _, name in ipairs(names) do
        local ver = 1
        if type(version) == "function" then
            ver = version(name)
        elseif type(version) == "number" then
            ver = version
        end

        local handle = MakeTranslatedHandle()

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
        handleToString[handle] = name
    end

    return root:Stringify({Indent = 2}), handleToString, stringToHandle
end