LSXHelpers = LSXHelpers or {}

---@return LSXNode
function LSXHelpers.new()
    local save = {
        version = {
            major = 4,
            minor = 8,
            revision = 0,
            build = 400,
            lslib_meta = "v1,bswap_guids,lsf_keys_adjacency"
        },
    }

    local root = LSXNode.new("save")
    local versionNode = root:AppendChild(
        LSXNode.new("version", {
            major = save.version.major,
            minor = save.version.minor,
            revision = save.version.revision,
            build = save.version.build,
            lslib_meta = save.version.lslib_meta
        })
    )
    versionNode:SetAttrOrder({"major", "minor", "revision", "build", "lslib_meta"})

    versionNode:AddComment("This file was generated by Script Extender")

    return root
end


function LSXHelpers.SerializeItem(guid, modName)
    local curLevel = _C().Level.LevelName
    local propData = EntityStore:GetEntity(guid)
    local entity = Ext.Entity.Get(guid) --[[@as EntityHandle]]
    if not propData then
        Error("MakePropLSX: No prop data found for GUID " .. tostring(guid))
        return nil
    end

    local root = LSXHelpers.new()
    if not root then
        Error("MakePropLSX: Failed to create LSX root node.")
        return nil
    end

    local regionNode = root:AppendChild(LSXNode.new("region", { id = "Templates" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "Templates" }))

    local firstChildren = templateNode:AppendChild(LSXNode.new("Children"))

    local gameObjectNode = firstChildren:AppendChild(LSXNode.new("node", { id = "GameObjects" }))

    local basicAttrs = {
        LSXHelpers.AttrNode("MapKey", "FixedString", guid),
        LSXHelpers.AttrNode("Name", "LSString", propData.DisplayName or TrimTail(propData.TemplateId, 37)),
        LSXHelpers.AttrNode("LevelName", "FixedString", curLevel),
        LSXHelpers.AttrNode("Type", "FixedString", "item"),
        LSXHelpers.AttrNode("TemplateName", "FixedString", TakeTailTemplate(propData.TemplateId)),
        LSXHelpers.AttrNode("GravityType", "uint8", entity.GravityDisabled and 1 or entity.GravityDisabledUntilMoved and 2 or 0), -- 0 = Enabled, 1 = Disabled, 2 = Disabled until moved
    }

    gameObjectNode:AppendChildren(basicAttrs)

    local secondChidren = gameObjectNode:AppendChild(LSXNode.new("Children"))
    local transformNode = secondChidren:AppendChild(LSXNode.new("node", { id = "Transform" }))


    local pos = {CGetPosition(guid)}
    local rot = {CGetRotation(guid)}
    local scale = {CGetScale(guid)}
    local smallestScale = math.min(scale[1], scale[2], scale[3])

    local transformAttrs = {
        LSXHelpers.AttrNode("Position", "fvec3", pos),
        LSXHelpers.AttrNode("RotationQuat", "fvec4", rot),
        LSXHelpers.AttrNode("Scale", "float", smallestScale),
    }

    transformNode:AppendChildren(transformAttrs)

    local layerListNode = secondChidren:AppendChild(LSXNode.new("node", { id = "LayerList" }))

    local layerFirstChildren = layerListNode:AppendChild(LSXNode.new("Children"))

    local layerNode = layerFirstChildren:AppendChild(LSXNode.new("node", { id = "Layer" }))

    local layerSecondChildren = layerNode:AppendChild(LSXNode.new("Children"))

    local objectNode = layerSecondChildren:AppendChild(LSXNode.new("node", { id = "Object", key = "MapKey" }))

    local layerAttr = {
        LSXHelpers.AttrNode("MapKey", "FixedString", curLevel),
    }

    objectNode:AppendChildren(layerAttr)

    if not modName then
        modName = "Mods"
    end

    return root:Stringify({ Indent = 2 }), guid
end

---@param marerialPresetUUID GUIDSTRING
---@param displayName string
---@param internalName string
---@param UIColor string
---@param presetType "EyeColor"|"HairColor"|"SkinColor"
---@return LSXNode
function LSXHelpers.BuildCCANode(marerialPresetUUID, displayName, internalName, UIColor, presetType)
    local node = LSXNode.new("node", { id = "CharacterCreation"..presetType })

    local attrs = {
        LSXHelpers.AttrNode("DisplayName", "TranslatedString", displayName),
        LSXHelpers.AttrNode("MaterialPresetUUID", "guid", marerialPresetUUID),
        LSXHelpers.AttrNode("Name", "FixedString", internalName),
        LSXHelpers.AttrNode("UIColor", "LSString", UIColor),
        LSXHelpers.AttrNode("UUID", "guid", Ext.Utils.GenerateGUID()),
    }

    node:AppendChildren(attrs)

    return node
end

---@param id any
---@param type LSXValueType
---@param value any
---@return LSXNode
function LSXHelpers.AttrNode(id, type, value)
    local attrNode = LSXNode.new("attribute", {
        id = id,
        type = type,
        value = value,
    })
    attrNode:SetAttrOrder({"id", "type", "value"})
    return attrNode
end

--- so this basically generates an XML string like this:
--- <?xml version="1.0" encoding="utf-8"?>
--- <contentList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
---   <content contentuid="generated-guid" version="1">name1</content>
---   <content contentuid="generated-guid" version="1">name2</content>
---  ...
--- </contentList>
---@param names string[]
---@param version number|fun(name:string):number
---@return string, table<string, string>, table<string, string>
function LSXHelpers.GenerateLocalization(names, version)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })
    local stringToHandle = {}
    local handleToString = {}

    for _, name in ipairs(names) do
        local ver = 1
        if type(version) == "function" then
            ver = version(name)
        elseif type(version) == "number" then
            ver = version
        end

        local handle = MakeTranslatedHandle()

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
        handleToString[handle] = name
    end

    return root:Stringify({Indent = 2}), handleToString, stringToHandle
end


local function createPresetParamAttrNodes(parameterName, value)
    local attrs = {}
    local valueType = DetermineLSXValueType(value)
    local saveValue = #value == 1 and value[1] or value
    if not valueType then
        Warning("CustomMaterialProxy: Could not determine LSX value type for preset parameter '" .. tostring(parameterName) .. "'. Skipping.")
        return nil
    end

    attrs = {
        LSXHelpers.AttrNode("Color", LSXValueType.bool, parameterName:find("Color") ~= nil or parameterName:find("Colour") ~= nil),
        LSXHelpers.AttrNode("Custom", LSXValueType.bool, false),
        LSXHelpers.AttrNode("Enabled", LSXValueType.bool, true),
        LSXHelpers.AttrNode("Value", valueType, saveValue),
        LSXHelpers.AttrNode("Parameter", LSXValueType.FixedString, parameterName),
    }
    
    return attrs
end

local function createPresetParameterNodes(matRes, parameters)
    local paramNodes = {} --[[@as LSXNode[] ]]
    for i,params in pairs(parameters) do
        for paramName,value in pairs(params) do
            local node = LSXNode.new("node", { id= PropTypeToField[i] })
            local attrs = createPresetParamAttrNodes(paramName, value)
            if not attrs then
                Warning("CustomMaterialProxy: Could not create LSX attribute nodes for parameter '" .. tostring(paramName) .. "'. Skipping parameter.")
            else
                node:AppendChildren(attrs)
                node:SortChildren(function (a,b) return a:GetAttribute("id") < b:GetAttribute("id") end)
                table.insert(paramNodes, node)
            end
        end
    end

    return paramNodes
end

---@param parameters table<1|2|3|4, table<string, number[]>>
---@param uuid GUIDSTRING
---@return string?
function LSXHelpers.SerializeMaterialPreset(parameters, uuid)
    local root = LSXHelpers.new()
    if not root then
        Error("CustomMaterialProxy: Could not create LSXTableNode for export.")
        return nil
    end

    local presetRegion = root:AppendChild(LSXNode.new("region", {id = "MaterialPresetBank"}))
    local presetNode = presetRegion:AppendChild(LSXNode.new("node", {id = "MaterialPresetBank"}))

    local childrenWrapper = LSXNode.new("children")
    presetNode:AppendChild(childrenWrapper)
    local resNode = LSXNode.new("node", {id="Resource"})
    childrenWrapper:AppendChild(resNode)

    local baseAttr = {
        LSXHelpers.AttrNode("ID", LSXValueType.FixedString, uuid),
        LSXHelpers.AttrNode("Name", LSXValueType.LSString, "Custom Material Preset"):AddComment("Change me!"),
        LSXHelpers.AttrNode("Localized", LSXValueType.bool, false),
        LSXHelpers.AttrNode("_OriginalFileVersion_", LSXValueType.int64, "144115198813274414"),
    }
    resNode:AppendChildren(baseAttr)

    resNode:SortChildren(function(a,b) return a:GetAttribute("id") < b:GetAttribute("id") end)

    local secondChildrenWrapper = LSXNode.new("children")
    resNode:AppendChild(secondChildrenWrapper)

    local presetsNode = LSXNode.new("node", {id="Presets"}, {
        LSXHelpers.AttrNode("MaterialResource", LSXValueType.FixedString, ""),
    })
    secondChildrenWrapper:AppendChild(presetsNode)

    local thirdChildrenWrapper = LSXNode.new("children") 
    presetsNode:AppendChild(thirdChildrenWrapper)

    local colorPresetNode = LSXNode.new("node", {id="ColorPreset"})
    thirdChildrenWrapper:AppendChild(colorPresetNode)
    local colorPresetAttrNodes = {
        LSXNode.new("attribute", {
            id = "ForcePresetValues",
            type = LSXValueType.bool,
            value = false,
        }),
        LSXNode.new("attribute", {
            id = "GroupName",
            type = LSXValueType.FixedString,
            value = "",
        }),
        LSXNode.new("attribute", {
            id = "MaterialPresetResource",
            type = LSXValueType.FixedString,
            value = "",
        }),
    }
    colorPresetNode:AppendChildren(colorPresetAttrNodes)

    local matePresetNode = LSXNode.new("node", {id="MaterialPresets"})
    thirdChildrenWrapper:AppendChild(matePresetNode)

    local paramNodes = createPresetParameterNodes(nil, parameters)

    if paramNodes then
        thirdChildrenWrapper:AppendChildren(paramNodes)
    end

    local xmlString = root:Stringify()

    return xmlString
end

local function compureVersionNumber(major, minor, revision, build)
    local version = major * 2^48 + minor * 2^32 + revision * 2^16 + build
    return tostring(version)
end

--- generate a meta.lsx file for a mod
---@param uuid string
---@param modName string
---@param author string
---@param version vec4
---@param description string
---@return LSXNode, LSXNode, LSXNode -- root, configNode, dependenciesNode
function LSXHelpers.BuildModMeta(uuid, modName, author, version, description)
    uuid = uuid or Uuid_v4()
    modName = modName or "Unnamed Mod"
    author = author or "Unknown Author"
    version = version or {1,0,0,0}
    description = description or ""

    local version64 = compureVersionNumber(version[1], version[2], version[3], version[4])

    local root = LSXHelpers.new()

    local configNode = root:AppendChild(LSXNode.new("Region", { id = "Config" }))

    local rootNode = configNode:AppendChild(LSXNode.new("node", { id = "root" }))

    local rootChildren = rootNode:AppendChild(LSXNode.new("Children"))

    local conflictNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Conflicts" }))

    local dependenciesNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Dependencies" }))

    local moduleIndoNode = rootChildren:AppendChild(LSXNode.new("node", { id = "ModuleInfo" }))

    local moduleInfoAttr = {
        LSXHelpers.AttrNode("Author", "LSString", author),
        LSXHelpers.AttrNode("Name", "LSString", modName),
        LSXHelpers.AttrNode("UUID", "FixedString", uuid),
        LSXHelpers.AttrNode("Version64", "int64", version64),
        LSXHelpers.AttrNode("Description", "LSString", description or ""),
        LSXHelpers.AttrNode("Folder", "LSString", modName),

        LSXHelpers.AttrNode("CharacterCreationLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("FileSize", "uint64", "0"),
        LSXHelpers.AttrNode("LobbyLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("MD5", "LSString", ""),
        LSXHelpers.AttrNode("PhotoBooth", "FixedString", ""),
        LSXHelpers.AttrNode("PublishHandle", "uint64", "0"),
        LSXHelpers.AttrNode("StartupLevelName", "FixedString", ""),
    }

    moduleIndoNode:AppendChildren(moduleInfoAttr)

    local moduleInfoChildren = moduleIndoNode:AppendChild(LSXNode.new("Children"))  

    --[[local publishVersionNode = moduleInfoChildren:AppendChild(LSXNode.new("node", { id = "PublishVersion" }))

    local publishVersion64Attr = publishVersionNode:AppendChild(
        LSXHelpers.AttrNode("Version64", "int64", version64)
    )]]

    return root, configNode, dependenciesNode
end