local LSXNode = LSXNode
LSXHelpers = LSXHelpers or {}

--- Create a new LSX save root node
---@return LSXNode
function LSXHelpers.new()
    local save = {
        version = {
            major = 4,
            minor = 8,
            revision = 0,
            build = 400,
            lslib_meta = "v1,bswap_guids,lsf_keys_adjacency"
        },
    }

    local root = LSXNode.new("save")
    local versionNode = root:AppendChild(
        LSXNode.new("version", {
            major = save.version.major,
            minor = save.version.minor,
            revision = save.version.revision,
            build = save.version.build,
            lslib_meta = save.version.lslib_meta
        })
    )
    versionNode:SetAttrOrder({ "major", "minor", "revision", "build", "lslib_meta" })

    versionNode:AddComment("This file was generated by Script Extender")
    versionNode:AddComment("If you have any issues, use LSX Validator: https://bg3.norbyte.dev/lsx-validator first.")

    return root
end

function LSXHelpers.GetPathAfterData(path)
    return path:match("Data[\\/](.*)") or path
end

--- @return LSXNode -- childrenNode
function LSXHelpers.BuildTemplatesRegionNode()
    return LSXHelpers.new():AppendChild(LSXNode.new("region", { id = "Templates" }))
        :AppendChild(LSXNode.new("node", { id = "Templates" }))
        :AppendChild(LSXHelpers.ChildrenNode())
end

function LSXHelpers.BuildLayerListNode(levelName)
    local layerNode = LSXNode.new("node", { id = "LayerList" })

    layerNode:AppendChild(LSXHelpers.ChildrenNode())
        :AppendChild(LSXNode.new("node", { id = "Layer" }))
        :AppendChild(LSXHelpers.ChildrenNode())
        :AppendChild(LSXNode.new("node", { id = "Object", key = "MapKey" }))
        :AppendChild(LSXHelpers.AttrNode("MapKey", "FixedString", levelName))

    return layerNode
end

--- build a game object LSX node for an entity GUID
--- @param guid any
--- @param templateType? "item"|"character"|"scenery"
--- @return LSXNode?
function LSXHelpers.BuildTemplate(guid, templateType)
    local entity = Ext.Entity.Get(guid) --[[@as EntityHandle]]
    local curLevel = entity.Level.LevelName
    local propData = EntityStore:GetStoredData(guid)

    if not templateType then
        if CIsItem(guid) then
            templateType = "item"
        elseif CIsCharacter(guid) then
            templateType = "character"
        elseif entity.Scenery then
            templateType = "scenery"
        else
            templateType = "item"
        end
    end

    if not propData then
        propData = {
            TemplateId = "",
            DisplayName = GetName(guid),
        }
    end

    local gameObjectNode = LSXNode.new("node", { id = "GameObjects" })

    local basicAttrs = {
        LSXHelpers.AttrNode("MapKey", "FixedString", guid),
        LSXHelpers.AttrNode("Name", "LSString", propData.DisplayName or TrimTail(propData.TemplateId, 37)),
        LSXHelpers.AttrNode("LevelName", "FixedString", curLevel),
        LSXHelpers.AttrNode("Type", "FixedString", templateType),
        LSXHelpers.AttrNode("TemplateName", "FixedString", TakeTailTemplate(propData.TemplateId)),
        LSXHelpers.AttrNode("GravityType", "uint8",
            entity.GravityDisabled and 1 or entity.GravityDisabledUntilMoved and 2 or 0),
        -- 0 = Enabled, 1 = Disabled, 2 = Disabled until moved
    }

    gameObjectNode:AppendChildren(basicAttrs)

    local secondChidren = gameObjectNode:AppendChild(LSXHelpers.ChildrenNode())
    local transformNode = secondChidren:AppendChild(LSXNode.new("node", { id = "Transform" }))

    local pos = { CGetPosition(guid) }
    local rot = { CGetRotation(guid) }
    local scale = { CGetScale(guid) }
    local smallestScale = math.min(scale[1], scale[2], scale[3])

    local transformAttrs = {
        LSXHelpers.AttrNode("Position", "fvec3", pos),
        LSXHelpers.AttrNode("RotationQuat", "fvec4", rot),
        LSXHelpers.AttrNode("Scale", "float", smallestScale),
    }

    transformNode:AppendChildren(transformAttrs)

    secondChidren:AppendChild(LSXHelpers.BuildLayerListNode(curLevel))

    return gameObjectNode
end

---@param id any
---@param attrType LSXValueType
---@param value any
---@param version number? for translatedstring
---@return LSXNode
function LSXHelpers.AttrNode(id, attrType, value, version)
    local valueKey = attrType == "TranslatedString" and "handle" or "value"

    local attrNode = LSXNode.new("attribute", {
        id = id,
        type = attrType,
        [valueKey] = value,
    })

    if version and attrType == "TranslatedString" then
        attrNode:SetAttribute("version", version)
    end

    attrNode:SetAttrOrder({ "id", "type", valueKey, "version" })
    return attrNode
end

function LSXHelpers.ChildrenNode()
    return LSXNode.new("children")
end

--- so this basically generates an XML localization file
---@param names string[]
---@param version number|fun(name:string):number
---@return string, table<string, string[]>, table<string, string> -- content, string -> handle[], handle -> string
function LSXHelpers.GenerateLocalization(names, version)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })
    local stringToHandles = {}
    local handleToString = {}

    for _, name in ipairs(names) do
        local ver = 1
        if type(version) == "function" then
            ver = version(name)
        elseif type(version) == "number" then
            ver = version
        end

        local handle = MakeTranslatedHandle()

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
        stringToHandles[name] = stringToHandles[name] or {}
        handleToString[handle] = name
        table.insert(stringToHandles[name], handle)
    end

    local content = root:Stringify({ Indent = 4, IncludeHeader = false })
    content = '<?xml version="1.0" ?>\n' .. content

    return content, stringToHandles, handleToString
end

--- @param handleToName table<TranslatedString, string>
--- @param versions table<TranslatedString, number>?
--- @return string
function LSXHelpers.BuildLocalization(handleToName, versions)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })

    for handle, name in pairs(handleToName) do
        local ver = 1
        if versions and versions[handle] then
            ver = versions[handle]
        end

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
    end

    local content = root:Stringify({ Indent = 4, IncludeHeader = false })
    content = '<?xml version="1.0" ?>\n' .. content

    return content
end

local function createPresetParamAttrNodes(parameterName, value)
    local attrs = {}
    local valueType = LSXHelpers.DetermineLSXValueType(value)
    local saveValue = #value == 1 and value[1] or value
    if not valueType then
        Warning("CustomMaterialProxy: Could not determine LSX value type for preset parameter '" ..
            tostring(parameterName) .. "'. Skipping.")
        return nil
    end

    attrs = {
        LSXHelpers.AttrNode("Color", LSXValueType.bool,
            parameterName:find("Color") ~= nil or parameterName:find("Colour") ~= nil),
        LSXHelpers.AttrNode("Custom", LSXValueType.bool, false),
        LSXHelpers.AttrNode("Enabled", LSXValueType.bool, true),
        LSXHelpers.AttrNode("Value", valueType, saveValue),
        LSXHelpers.AttrNode("Parameter", LSXValueType.FixedString, parameterName),
    }

    return attrs
end

local function createPresetParameterNodes(matRes, parameters)
    local paramNodes = {} --[[@as LSXNode[] ]]
    for i, params in pairs(parameters) do
        for paramName, value in pairs(params) do
            local node = LSXNode.new("node", { id = PropTypeToField[i] })
            local attrs = createPresetParamAttrNodes(paramName, value)
            if not attrs then
                Warning("CustomMaterialProxy: Could not create LSX attribute nodes for parameter '" ..
                    tostring(paramName) .. "'. Skipping parameter.")
            else
                node:AppendChildren(attrs)
                node:SortChildren(function(a, b) return a:GetAttribute("id") < b:GetAttribute("id") end)
                table.insert(paramNodes, node)
            end
        end
    end

    return paramNodes
end

---@param parameters table<1|2|3|4, table<string, number[]>>
---@param uuid GUIDSTRING
---@param internalName string
---@return LSXNode
function LSXHelpers.BuildMaterialPresetResourceNode(parameters, uuid, internalName)
    local root = LSXNode.new("node", { id = "Resource" })

    local baseAttr = {
        LSXHelpers.AttrNode("ID", LSXValueType.FixedString, uuid),
        LSXHelpers.AttrNode("Name", LSXValueType.LSString, internalName),
        LSXHelpers.AttrNode("Localized", LSXValueType.bool, false),
        LSXHelpers.AttrNode("_OriginalFileVersion_", LSXValueType.int64, "144115198813274414"),
    }
    root:AppendChildren(baseAttr)

    root:SortChildren(function(a, b) return a:GetAttribute("id") < b:GetAttribute("id") end)

    local childrenNode = root:AppendChild(LSXHelpers.ChildrenNode())

    local presetsNode = childrenNode:AppendChild(LSXNode.new("node", { id = "Presets" }, {
        LSXHelpers.AttrNode("MaterialResource", LSXValueType.FixedString, ""),
    }))

    local thirdChildrenWrapper = presetsNode:AppendChild(LSXHelpers.ChildrenNode())

    local colorPresetNode = thirdChildrenWrapper:AppendChild(LSXNode.new("node", { id = "ColorPreset" }))

    local colorPresetAttrNodes = {
        LSXHelpers.AttrNode("ForcePresetValues", LSXValueType.bool, false),
        LSXHelpers.AttrNode("GroupName", LSXValueType.FixedString, ""),
        LSXHelpers.AttrNode("MaterialPresetResource", LSXValueType.FixedString, ""),
    }
    colorPresetNode:AppendChildren(colorPresetAttrNodes)

    local matePresetNode = LSXNode.new("node", { id = "MaterialPresets" })
    thirdChildrenWrapper:AppendChild(matePresetNode)

    local paramNodes = createPresetParameterNodes(nil, parameters)

    if paramNodes then
        thirdChildrenWrapper:AppendChildren(paramNodes)
    end

    return root
end

function LSXHelpers.DetermineLSXValueType(value)
    if type(value) == "boolean" then
        return LSXValueType.bool
    elseif type(value) == "number" then
        return LSXValueType.float
    elseif type(value) == "string" then
        return LSXValueType.FixedString
    elseif type(value) == "table" then
        if #value == 1 then
            return LSXValueType.float
        elseif #value == 2 then
            return LSXValueType.fvec2
        elseif #value == 3 then
            return LSXValueType.fvec3
        elseif #value == 4 then
            return LSXValueType.fvec4
        end
    end

    return LSXValueType.LSString
end

local function createParameterAttrNodes(paramObj, overrideValue)
    local attrs = {}
    for k, v in pairs(paramObj) do
        local valueType = LSXHelpers.DetermineLSXValueType(v)
        if not valueType then
            Warning("CustomMaterialProxy: Could not determine LSX value type for parameter '" ..
                tostring(paramObj.ParameterName) .. "'. Skipping.")
            return nil
        end

        local value = v
        if k == "Value" and overrideValue then
            value = #overrideValue == 1 and overrideValue[1] or overrideValue
        end

        local attr = LSXNode.new("attribute", {
            id = k,
            type = valueType,
            value = value
        })
        attr:SetAttrOrder({ "id", "type", "value" })

        table.insert(attrs, attr)
    end
    return attrs
end

---@param matRes ResourceMaterialResource
---@param parameters table<number, table<string, number[]>>
---@return LSXNode|nil
local function createParameterNodes(matRes, parameters)
    local paramNodes = {} --[[@as LSXNode[] ]]
    local paramList = {
        matRes.ScalarParameters,
        matRes.Vector2Parameters,
        matRes.Vector3Parameters,
        matRes.VectorParameters,
        matRes.Texture2DParameters,
        matRes.VirtualTextureParameters
    }
    local indexToNodeName = {
        [1] = "ScalarParameters",
        [2] = "Vector2Parameters",
        [3] = "Vector3Parameters",
        [4] = "VectorParameters",
        [5] = "Texture2DParameters",
        [6] = "VirtualTextureParameters"
    }

    for i, params in pairs(paramList) do
        for _, param in pairs(params) do
            local node = LSXNode.new("node", { id = indexToNodeName[i] })
            local paramName = param.ParameterName
            local value = nil
            if i < 5 then
                value = parameters[i][paramName] or param.Value
                if type(value) == "number" then
                    value = { value }
                end
            end
            local attrs = createParameterAttrNodes(param, value)
            if not attrs then
                Warning("CustomMaterialProxy: Could not create LSX attribute nodes for parameter '" ..
                    tostring(paramName) .. "'. Skipping parameter.")
            else
                node:AppendChildren(attrs)
                node:SortChildren(function(a, b) return a:GetAttribute("id") < b:GetAttribute("id") end)
                table.insert(paramNodes, node)
            end
        end
    end

    return paramNodes
end


---@param params RB_ParameterSet
---@param matName GUIDSTRING
---@return LSXNode?
function LSXHelpers.BuildMaterialResource(params, matName)
    local root = LSXHelpers.new()
    if not root then
        Error("CustomMaterialProxy: Could not create LSXTableNode for export.")
        return nil
    end

    local matRes = Ext.Resource.Get(matName, "Material") --[[@as ResourceMaterialResource]]
    if not matRes then
        Error("CustomMaterialProxy: Could not find origin material resource for '" ..
            tostring(matName) .. "'. Cannot export to LSX.")
        return nil
    end

    local matRegion = root:AppendChild(LSXNode.new("region", { id = "MaterialBank" }))
    local matNode = matRegion:AppendChild(LSXNode.new("node", { id = "MaterialBank" }))
    local childrenWrapper = matNode:AppendChild(LSXNode.new("children"))
    local resNode = childrenWrapper:AppendChild(LSXNode.new("node", { id = "Resource" }))

    local sourceFile = LSXHelpers.GetPathAfterData(matRes.SourceFile or "")
    local baseAttr = {
        LSXHelpers.AttrNode("ID", "guid", matName),
        LSXHelpers.AttrNode("Name", "LSString", "Custom Material"),
        LSXHelpers.AttrNode("SourceFile", "LSString", sourceFile),
        LSXHelpers.AttrNode("MaterialType", "uint8", matRes.MaterialType or 0),
        LSXHelpers.AttrNode("DiffusionProfileUUID", "FixedString", matRes.bUseDiffusionProfile or ""),
    }
    resNode:AppendChildren(baseAttr)
    resNode:SortChildren(function(a, b) return a:GetAttribute("id") < b:GetAttribute("id") end)

    local secondChildrenWrapper = LSXNode.new("children")
    resNode:AppendChild(secondChildrenWrapper)
    local paramNodes = createParameterNodes(matRes, params)
    if paramNodes then
        secondChildrenWrapper:AppendChildren(paramNodes)
    end

    return root
end

---@return LSXNode -- childrenNode
function LSXHelpers.BuildMaterialPresetBank()
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = "MaterialPresetBank" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "MaterialPresetBank" }))

    local childrenNode = templateNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode
end

---@param displayName string the handle of the translated string
---@param internalName string
---@param uiColor vec4
---@param matPUuid GUIDSTRING
---@param uuid GUIDSTRING
---@param presetType "CharacterCreationEyeColors"|"CharacterCreationHairColors"|"CharacterCreationSkinColors"
---@return LSXNode
function LSXHelpers.BuildCCAPresetNode(displayName, internalName, uiColor, matPUuid, uuid, presetType)
    if presetType:sub(-1) == "s" then
        presetType = presetType:sub(1, -2)
    end

    local node = LSXNode.new("node", { id = presetType })

    if #uiColor < 4 then
        uiColor = { uiColor[1] or 1, uiColor[2] or 1, uiColor[3] or 1, uiColor[4] or 1 }
    end

    local hex = RGBAToHex(uiColor[1], uiColor[2], uiColor[3], uiColor[4])

    local attrs = {
        LSXHelpers.AttrNode("DisplayName", "TranslatedString", displayName, 1),
        LSXHelpers.AttrNode("MaterialPresetUUID", "guid", matPUuid),
        LSXHelpers.AttrNode("Name", "FixedString", internalName),
        LSXHelpers.AttrNode("UUID", "guid", uuid),
        LSXHelpers.AttrNode("UIColor", "LSString", hex),
    }

    node:AppendChildren(attrs)

    return node
end

---@param presetsType "CharacterCreationEyeColors"|"CharacterCreationHairColors"|"CharacterCreationSkinColors"
---@return LSXNode -- saveNode
function LSXHelpers.BuildCCAPresetsRegionNode(presetsType)
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = presetsType }))

    local rootNode = regionNode:AppendChild(LSXNode.new("node", { id = "root" }))

    local childrenNode = rootNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode
end

--- generate a meta.lsx file for a mod
---@param uuid string
---@param modName string
---@param author string
---@param version vec4
---@param description string
---@return LSXNode, LSXNode, LSXNode -- root, conflictNode, dependenciesNode
function LSXHelpers.BuildModMeta(uuid, modName, internalName, author, version, description)
    uuid = uuid or Uuid_v4()
    modName = modName or "Unnamed Mod"
    author = author or "Unknown Author"
    version = version or { 1, 0, 0, 0 }
    description = description or ""

    local version64 = ComputeVersion64(version[1], version[2], version[3], version[4]) --[[@as number|string]]

    local root = LSXHelpers.new()
    root:GetChild(1):SetAttribute("lslib_meta", nil)

    local configNode = root:AppendChild(LSXNode.new("region", { id = "Config" }))

    local rootNode = configNode:AppendChild(LSXNode.new("node", { id = "root" }))

    local rootChildren = rootNode:AppendChild(LSXHelpers.ChildrenNode())

    local conflictNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Conflicts" }))

    local dependenciesNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Dependencies" }))

    local moduleIndoNode = rootChildren:AppendChild(LSXNode.new("node", { id = "ModuleInfo" }))

    local moduleInfoAttr = {
        LSXHelpers.AttrNode("Author", "LSString", author),
        LSXHelpers.AttrNode("CharacterCreationLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("Description", "LSString", description),
        LSXHelpers.AttrNode("Folder", "LSString", internalName),
        LSXHelpers.AttrNode("LobbyLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("MD5", "LSString", ""),
        LSXHelpers.AttrNode("MainMenuBackgroundVideo", "FixedString", ""),
        LSXHelpers.AttrNode("MenuLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("Name", "LSString", modName),
        LSXHelpers.AttrNode("NumPlayers", "uint8", "4"),
        LSXHelpers.AttrNode("PhotoBooth", "FixedString", ""),
        LSXHelpers.AttrNode("StartupLevelName", "FixedString", ""),
        LSXHelpers.AttrNode("Tags", "LSString", ""),
        LSXHelpers.AttrNode("Type", "FixedString", "Add-on"),
        LSXHelpers.AttrNode("UUID", "FixedString", uuid),
        LSXHelpers.AttrNode("Version64", "int64", version64),
    }

    moduleIndoNode:AppendChildren(moduleInfoAttr)

    local moduleInfoChildren = moduleIndoNode:AppendChild(LSXHelpers.ChildrenNode())

    local publishVersionNode = moduleInfoChildren:AppendChild(LSXNode.new("node", { id = "PublishVersion" }))

    local publishVersion64Attr = publishVersionNode:AppendChild(
        LSXHelpers.AttrNode("Version64", "int64", version64)
    )

    return root, conflictNode, dependenciesNode
end
