local LSXNode = LSXNode
LSXHelpers = LSXHelpers or {}

--- Create a new LSX save root node
---@return LSXNode
function LSXHelpers.new()
    local save = {
        version = {
            major = 4,
            minor = 8,
            revision = 0,
            build = 400,
            lslib_meta = "v1,bswap_guids,lsf_keys_adjacency"
        },
    }

    local root = LSXNode.new("save")
    local versionNode = root:AppendChild(
        LSXNode.new("version", {
            major = save.version.major,
            minor = save.version.minor,
            revision = save.version.revision,
            build = save.version.build,
            lslib_meta = save.version.lslib_meta
        })
    )
    versionNode:SetAttrOrder({ "major", "minor", "revision", "build", "lslib_meta" })

    versionNode:AddComment("This file was generated by Script Extender")

    return root
end

local attrOrder = {
    "id",
    "type",
    "value",
    "handle",
    "version",
}
---@param id any
---@param attrType LSValueType
---@param value any
---@param version number? for translatedstring
---@return LSXNode
function LSXHelpers.AttrNode(id, attrType, value, version)
    local valueKey = attrType == "TranslatedString" and "handle" or "value"

    if attrType == "float" or attrType == "double" then
        value = tostring(value)
        if not value:find("%.") then
            value = value .. ".0"
        end
    end

    local attrNode = LSXNode.new("attribute", {
        id = id,
        type = attrType,
        [valueKey] = value,
    })

    if version and attrType == "TranslatedString" then
        attrNode:SetAttribute("version", version)
    end

    attrNode:SetAttrOrder(attrOrder)
    return attrNode
end

local lsattrNode = LSXHelpers.AttrNode

function LSXHelpers.GetPathAfterData(path)
    return path:match("Data[\\/](.*)") or path
end

--- @return LSXNode -- childrenNode
function LSXHelpers.BuildTemplatesRegionNode()
    return LSXHelpers.new():AppendChild(LSXNode.new("region", { id = "Templates" }))
        :AppendChild(LSXNode.new("node", { id = "Templates" }))
        :AppendChild(LSXHelpers.ChildrenNode())
end

function LSXHelpers.BuildLayerListNode(levelName)
    local layerNode = LSXNode.new("node", { id = "LayerList" })

    layerNode:AppendChild(LSXHelpers.ChildrenNode())
        :AppendChild(LSXNode.new("node", { id = "Layers" }))
        :AppendChild(LSXHelpers.ChildrenNode())
        :AppendChild(LSXNode.new("node", { id = "Object", key = "MapKey" })):SetAttrOrder({ "id", "key" })
        :AppendChild(lsattrNode("MapKey", "FixedString", levelName))

    return layerNode
end

--- @param node LSXNode
function LSXHelpers.SetAttrNode(node, attrId, attrType, value)
    local attrNode = node:SearchChild(function(child)
        if child:GetName() ~= "attribute" then return false end
        return child:GetAttribute("id") == attrId
    end)
    if not attrNode then
        attrNode = lsattrNode(attrId, attrType, value)
        node:AppendChild(attrNode)
    else
        attrNode:SetAttribute("type", attrType)
        attrNode:SetAttribute("value", value)
    end
end

--- @param data EntityData
--- @return LSXNode[]
local function buildItemAttrs(data)
    local attrs = {
        lsattrNode("CanBeMoved", "bool", data.Movable and true or false),
        lsattrNode("IsInteractionDisabled", "bool", data.CanInteract and false or true),
        lsattrNode("GravityType", "uint8", data.DisableGravityUntilMoved and 2 or data.Gravity and 0 or 1), -- 0 = Enabled, 1 = Disabled, 2 = Disabled until moved
        lsattrNode("CanBePickedUp", "bool", data.CanBeLooted and true or false),
    }

    return attrs
end

local function buildCharacterAttrs(entity)
    local attrs = {
        lsattrNode("CanFight", "bool", false), -- default to false for now
    }
    return attrs
end

--- @type table<string, fun(entity:EntityData):LSXNode[]>
local uinqueAttrs = {
    item = buildItemAttrs,
    character = buildCharacterAttrs,
}

--- @class WanderConfig
--- @field Area number?
--- @field WanderMin number
--- @field WanderMax number
--- @field SleepMin number?
--- @field SleepMax number?

--- build a local template
--- @param guid any
--- @param internalName string
--- @param displayNameHandle string?
--- @param entData EntityData
--- @return LSXNode?, {Uuid:string, TemplateType:string, LSXNode:LSXNode}[]?
function LSXHelpers.BuildTemplate(guid, entData, internalName, displayNameHandle)
    local curLevel = entData.LevelName
    local pos = entData.Position or { CGetPosition(guid) }
    local rot = entData.Rotation or { CGetRotation(guid) }
    local scale = entData.Scale or ({ CGetScale(guid) })[1]

    local templateType = entData.TemplateType
    local templateUuid = TakeTailTemplate(entData.TemplateId)
    local others = {}

    if not templateType then return end

    local templateRegion = LSXHelpers.BuildTemplatesRegionNode()
    local gameObjectNode = templateRegion:AppendChild(LSXNode.new("node", { id = "GameObjects" }))

    local basicAttrs = {
        lsattrNode("MapKey", "FixedString", guid),
        lsattrNode("Name", "LSString", internalName),
        lsattrNode("LevelName", "FixedString", curLevel),
        lsattrNode("Type", "FixedString", templateType),
        lsattrNode("TemplateName", "FixedString", templateUuid),
        lsattrNode("Flag", "uint8", entData.Flag or 1),
        lsattrNode("ParentTemplateId", "FixedString", templateUuid),
    }
    if templateType == "item" and entData.OverrideVisualUuid then
        gameObjectNode:InsertChild(LSXHelpers.AttrNode("VisualTemplate", "FixedString", entData.OverrideVisualUuid), 1)
    end

    if displayNameHandle then
        table.insert(basicAttrs, lsattrNode("DisplayName", "TranslatedString", displayNameHandle, 1))
    end

    if uinqueAttrs[templateType] then
        local customAttrs = uinqueAttrs[templateType](entData) --[[@as LSXNode[] ]]
        for _, attrNode in ipairs(customAttrs) do
            table.insert(basicAttrs, attrNode)
        end
    end

    gameObjectNode:AppendChildren(basicAttrs)

    local secondChidren = gameObjectNode:AppendChild(LSXHelpers.ChildrenNode())
    local transformNode = secondChidren:AppendChild(LSXNode.new("node", { id = "Transform" }))

    local transformAttrs = {
        lsattrNode("Position", "fvec3", pos),
        lsattrNode("RotationQuat", "fvec4", rot),
        lsattrNode("Scale", "float", scale),
    }

    transformNode:AppendChildren(transformAttrs)

    secondChidren:AppendChild(LSXHelpers.BuildLayerListNode(curLevel))

    if templateType == "character" then
        secondChidren:AppendChild(LSXNode.new("node", { id = "LocomotionParams" }))
        
        if entData.OverrideVisualUuid then
            gameObjectNode:InsertChild(LSXHelpers.AttrNode("CharacterVisualResourceID", "FixedString", entData.OverrideVisualUuid), 1)
        end

        if not entData.WanderConfig then
            return gameObjectNode, others
        end

        local wanderTriggerUuid = Uuid_v4()
        local wanderParams = entData.WanderConfig or {}
        local triggerName = internalName .. "_WanderTrigger"
        local anubisName = triggerName .. "_" .. wanderTriggerUuid

        local triggerNode = LSXHelpers.BuildBoxTrigger(pos, rot, wanderParams.Extents or {10,5,10},
            curLevel, triggerName, wanderTriggerUuid)

        local anubisAttr, anubisParams = AnubisHelpers.BuildWanderParams(
            entData.WanderConfig.WanderMin or 3,
            entData.WanderConfig.WanderMax or 6,
            entData.WanderConfig.SleepMin or 8,
            entData.WanderConfig.SleepMax or 14,
            anubisName)

        gameObjectNode:InsertChild(anubisAttr, 1)
        secondChidren:AppendChild(anubisParams)
        table.insert(others, { Uuid = wanderTriggerUuid, TemplateType = "trigger", LSXNode = triggerNode })
    end

    return gameObjectNode, others
end


function LSXHelpers.BuildRootTemplate(srcUuid, uuid, internalName, override)
    srcUuid = TakeTailTemplate(srcUuid)
    override = override or {}
    local templateRegion = LSXHelpers.BuildTemplatesRegionNode()
    local gameObjectNode = templateRegion:AppendChild(LSXNode.new("node", { id = "GameObjects" }))

    local parentType = Ext.Template.GetTemplate(srcUuid).TemplateType

    local basicAttrs = {
        lsattrNode("Type", "FixedString", parentType),
        lsattrNode("MapKey", "FixedString", uuid),
        lsattrNode("Name", "LSString", internalName),
        lsattrNode("ParentTemplateId", "FixedString", srcUuid),
    }

    if override.VisualTemplate then
        table.insert(basicAttrs, lsattrNode("VisualTemplate", "FixedString", override.VisualTemplate))
    end

    gameObjectNode:AppendChildren(basicAttrs)

    return gameObjectNode
end

function LSXHelpers.ChildrenNode()
    return LSXNode.new("children")
end

---@param names string[]
---@param version number|fun(name:string):number
---@return string, table<string, string[]>, table<string, string> -- content, string -> handle[], handle -> string
function LSXHelpers.GenerateLocalization(names, version)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })
    local stringToHandles = {}
    local handleToString = {}

    for _, name in ipairs(names) do
        local ver = 1
        if type(version) == "function" then
            ver = version(name)
        elseif type(version) == "number" then
            ver = version
        end

        local handle = MakeTranslatedHandle()

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
        stringToHandles[name] = stringToHandles[name] or {}
        handleToString[handle] = name
        table.insert(stringToHandles[name], handle)
    end

    local content = root:Stringify({ Indent = 4, IncludeHeader = false })
    content = '<?xml version="1.0" ?>\n' .. content

    return content, stringToHandles, handleToString
end

--- @param handleToName table<TranslatedString, string>
--- @param versions table<TranslatedString, number>?
--- @return string
function LSXHelpers.BuildLocalization(handleToName, versions)
    local root = LSXNode.new("contentList", {
        ["xmlns:xsd"] = "http://www.w3.org/2001/XMLSchema",
        ["xmlns:xsi"] = "http://www.w3.org/2001/XMLSchema-instance",
    })

    for handle, name in pairs(handleToName) do
        local ver = 1
        if versions and versions[handle] then
            ver = versions[handle]
        end

        local contentNode = LSXNode.new("content", {
            contentuid = handle,
            version = ver
        })
        contentNode:SetInnerText(name)
        root:AppendChild(contentNode)
    end

    local content = root:Stringify({ Indent = 4, IncludeHeader = false })
    content = '<?xml version="1.0" ?>\n' .. content

    return content
end

function LSXHelpers.LSValueType(value)
    if type(value) == "boolean" then
        return LSValueType.bool
    elseif type(value) == "number" then
        return LSValueType.float
    elseif type(value) == "string" then
        return LSValueType.FixedString
    elseif type(value) == "table" then
        if #value == 1 then
            return LSValueType.float
        elseif #value == 2 then
            return LSValueType.fvec2
        elseif #value == 3 then
            return LSValueType.fvec3
        elseif #value == 4 then
            return LSValueType.fvec4
        end
    end

    return LSValueType.LSString
end

---@return LSXNode, LSXNode -- childrenNode, regionNode
function LSXHelpers.BuildMaterialPresetBank()
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = "MaterialPresetBank" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "MaterialPresetBank" }))

    local childrenNode = templateNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode, regionNode
end

--- @return LSXNode, LSXNode -- childrenNode, regionNode
function LSXHelpers.BuildMaterialBank()
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = "MaterialBank" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "MaterialBank" }))

    local childrenNode = templateNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode, regionNode
end

--- @return LSXNode, LSXNode -- childrenNode, regionNode
function LSXHelpers.BuildCharacterVisualBank()
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = "CharacterVisualBank" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "CharacterVisualBank" }))

    local childrenNode = templateNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode, regionNode
end

--- @return LSXNode, LSXNode -- childrenNode, regionNode
function LSXHelpers.BuildVisualBank()
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = "VisualBank" }))
    local templateNode = regionNode:AppendChild(LSXNode.new("node", { id = "VisualBank" }))

    local childrenNode = templateNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode, regionNode
end

---@param displayName string the handle of the translated string
---@param internalName string
---@param uiColor vec4
---@param matPUuid GUIDSTRING
---@param uuid GUIDSTRING
---@param presetType "CharacterCreationEyeColors"|"CharacterCreationHairColors"|"CharacterCreationSkinColors"
---@return LSXNode
function LSXHelpers.BuildCCColorNode(displayName, internalName, uiColor, matPUuid, uuid, presetType)
    if presetType:sub(-1) == "s" then
        presetType = presetType:sub(1, -2)
    end

    local node = LSXNode.new("node", { id = presetType })

    if #uiColor < 4 then
        uiColor = { uiColor[1] or 1, uiColor[2] or 1, uiColor[3] or 1, uiColor[4] or 1 }
    end

    local hex = RGBAToHex(uiColor[1], uiColor[2], uiColor[3], uiColor[4])

    local attrs = {
        lsattrNode("DisplayName", "TranslatedString", displayName, 1),
        lsattrNode("MaterialPresetUUID", "guid", matPUuid),
        lsattrNode("Name", "FixedString", internalName),
        lsattrNode("UUID", "guid", uuid),
        lsattrNode("UIColor", "LSString", hex),
    }

    node:AppendChildren(attrs)

    return node
end

---@param presetsType "CharacterCreationEyeColors"|"CharacterCreationHairColors"|"CharacterCreationSkinColors"
---@return LSXNode -- saveNode
function LSXHelpers.BuildCCColorRegionNode(presetsType)
    local saveNode = LSXHelpers.new()

    local regionNode = saveNode:AppendChild(LSXNode.new("region", { id = presetsType }))

    local rootNode = regionNode:AppendChild(LSXNode.new("node", { id = "root" }))

    local childrenNode = rootNode:AppendChild(LSXHelpers.ChildrenNode())

    return childrenNode
end

--- generate a meta.lsx file for a mod
---@param uuid string
---@param modName string
---@param author string
---@param version vec4
---@param description string
---@return LSXNode, LSXNode, LSXNode -- root, conflictNode, dependenciesNode
function LSXHelpers.BuildModMeta(uuid, modName, internalName, author, version, description)
    uuid = uuid or Uuid_v4()
    modName = modName or "Unnamed Mod"
    author = author or "Unknown Author"
    version = version or { 1, 0, 0, 0 }
    description = description or ""

    local version64 = ComputeVersion64(version[1], version[2], version[3], version[4]) --[[@as number|string]]

    local root = LSXHelpers.new()
    root:GetChild(1):SetAttribute("lslib_meta", nil)

    local configNode = root:AppendChild(LSXNode.new("region", { id = "Config" }))

    local rootNode = configNode:AppendChild(LSXNode.new("node", { id = "root" }))

    local rootChildren = rootNode:AppendChild(LSXHelpers.ChildrenNode())

    local conflictNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Conflicts" }))

    local dependenciesNode = rootChildren:AppendChild(LSXNode.new("node", { id = "Dependencies" }))

    local moduleIndoNode = rootChildren:AppendChild(LSXNode.new("node", { id = "ModuleInfo" }))

    local moduleInfoAttr = {
        lsattrNode("Author", "LSString", author),
        lsattrNode("CharacterCreationLevelName", "FixedString", ""),
        lsattrNode("Description", "LSString", description),
        lsattrNode("Folder", "LSString", internalName),
        lsattrNode("LobbyLevelName", "FixedString", ""),
        lsattrNode("MD5", "LSString", ""),
        lsattrNode("MainMenuBackgroundVideo", "FixedString", ""),
        lsattrNode("MenuLevelName", "FixedString", ""),
        lsattrNode("Name", "LSString", modName),
        lsattrNode("NumPlayers", "uint8", "4"),
        lsattrNode("PhotoBooth", "FixedString", ""),
        lsattrNode("StartupLevelName", "FixedString", ""),
        lsattrNode("Tags", "LSString", ""),
        lsattrNode("Type", "FixedString", "Add-on"),
        lsattrNode("UUID", "FixedString", uuid),
        lsattrNode("Version64", "int64", version64),
    }

    moduleIndoNode:AppendChildren(moduleInfoAttr)

    local moduleInfoChildren = moduleIndoNode:AppendChild(LSXHelpers.ChildrenNode())

    local publishVersionNode = moduleInfoChildren:AppendChild(LSXNode.new("node", { id = "PublishVersion" }))

    local publishVersion64Attr = publishVersionNode:AppendChild(
        lsattrNode("Version64", "int64", version64)
    )

    return root, conflictNode, dependenciesNode
end

---@param pos vec3
---@param extents vec3
---@param levelName string
---@param name string
---@return LSXNode
function LSXHelpers.BuildBoxTrigger(pos, rot, extents, levelName, name, uuid)
    local templateNode = LSXHelpers.BuildTemplatesRegionNode()
    local triggerNode = templateNode:AppendChild(LSXNode.new("node", { id = "GameObjects" }))

    local baseAttr = {
        lsattrNode("MapKey", "FixedString", uuid),
        lsattrNode("Extents", "fvec3", extents),
        lsattrNode("Flag", "int32", 1),
        lsattrNode("LevelName", "FixedString", levelName),
        lsattrNode("Name", "LSString", name),
        lsattrNode("OnlyCharacterEvents", "bool", false),
        lsattrNode("OnlyOsirisEvents", "bool", false),
        lsattrNode("TemplateName", "FixedString", "987b8a4d-2208-4bae-a92d-706db0e593e8"), -- BoxTrigger template
        lsattrNode("Type", "FixedString", "trigger"),
        lsattrNode("_OriginalFileVersion_", "int64", "144115207403209026"),
    }

    triggerNode:AppendChildren(baseAttr)
    local children = triggerNode:AppendChild(LSXHelpers.ChildrenNode())

    children:AppendChild(LSXNode.new("node", { id = "FadeChildren" }))
        :GetParent()
        :AppendChild(LSXHelpers.BuildLayerListNode(levelName))
        :GetParent()
        :AppendChild(LSXNode.new("node", { id = "Transform" }))
        :AppendChildren({
            lsattrNode("Position", "fvec3", pos),
            lsattrNode("RotationQuat", "fvec4", rot),
            lsattrNode("Scale", "float", 1),
        })

    return templateNode
end
