RequireFiles("Client/UI/Components/", {
    "MaterialTab",
    "VisualTab",
    "StatsParser",
    "StatsRenderer",
    "IconBrowser/_init",
    "ItemBrowser",
    "EffectBrowser",
    "RootTemplateBrowser",
    "CCAVBrowser",
    "EntityTab",
    "EffectTab",
    "CustomEffectTab",
    "StatsTab",
    "MaterialPresetsMenu",
    "TemplateExportMenu",
    "ResourceEditor",
})
